service: fathom-chat
image: 3dnara/fathom-chat

servers:
  web:
    - 45.32.115.150

volumes:
  - fathom-chat-storage:/rails/storage

proxy:
  ssl: true
  host: fathom-chat.work

accessories:
  redis:
    image: redis:7-alpine
    host: 45.32.115.150
    port: "127.0.0.1:6379:6379"
    cmd: redis-server
    volumes:
      - redis_data:/data

registry:
  username: 3dnara
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_LOG_LEVEL: error
    REDIS_URL: redis://fathom-chat-redis:6379

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64